# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b391e635d6c2d9e86ff0b466d35491f28d2599467289d20af4674301063a4a8337a29b4245543449e107ecdf00341bbfa3ae94016d5fe9131fdf5a69998dbd3

test:
  secret_key_base: 99dd7b975ae83d6a2ce148464f995e0e0aacfd0188e3c5f899a3922341a7a949c92d71fb826a5333a5c1ee7bb26b98ddc942c08d14551c1d31b72cf23f78a854

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
